server:
  port: 9016

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
    routes:
      - id: sidecar-service
        uri: lb://sidecar-service
        predicates:
          - Path=/sidecar-service/**
  zipkin:
    base-url: http://127.0.0.1:9411
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1.0

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    org.springframework.cloud.sleuth: debug